### PR TITLE
AddItemAt method to add a menu item at the specified index

### PR DESCRIPTION
**Pull request by tomilovsenya**
This can help change menu's items dynamically at any index. Works just fine for me.

My code:
`                    controllerMain.RemoveItemAt(1);
                    controllerMain.AddItemAt(mainSetAssault, 1);`

Video here: [YouTube](https://www.youtube.com/watch?v=lBh_QoDGiC8)

### CODE REVIEW

**Comment by justalemon** [comment]
I don't see why would you need this, any context?

**Comment by karimcambridge** [comment]
Never had a use case for this either

**Comment by tomilovsenya** [comment]
@justalemon, @karimcambridge, what about the video in the OP? Sure, it would not be used in any menu here and there, but I think adding it won't be a big loss.

**Comment by karimcambridge** [comment]
I didn't really understand it lol, you we're just copying the list in `Score Set` into `Track` using the index right? Probably using `IndexChange` event I guess.

Idk it's cool, it doesn't hurt to have.

**Comment by tomilovsenya** [comment]
@karimcambridge, my code is in the OP. When the Set changes, the Track item at index 1 is deleted and its copy with another (pre-created) collection of Tracks is inserted at index 1. If I used the AddItem method instead, the item would be inserted in the end of the menu, which is not what I need.

**Comment by karimcambridge** [comment]
Right right, yes we understand, imo it should be added to 'complete' the feature set (bad choice of words but ye u get me).

**Comment by justalemon** [comment]
Still, I don't feel that this is required because of the following reasons:

1. The menus should be created with the required items and then update their content during runtime.
1. In your case, you can edit the items of the Track `UIMenuListItem` (see #95)

**Comment by tomilovsenya** [comment]
@justalemon, didn't know that was possible. I'll se how it'd work, and if it's fine I will no longer need the AddItemAt method – but no idea if it won't be useful for someone else.

**Comment by karimcambridge** [comment]
That's true, you can just inject them using the variable `MenuItems` the same way.. but it doesn't hurt still.

**Comment by justalemon** [comment]
I'm going to keep this open for the time being. If you need to change the items of UIMenuListItem during runtime, wait for the release of the new version (aprox 3 days) that includes #95.

**Comment by justalemon** [comment]
#95 is now part of the 1.9 release, so this is no longer needed.

**Pull request closed without merging**
