### PR TITLE
Fixed a typo in GetScreenResolutionMaintainRatio()

### PR DESCRIPTION
**Pull request by tiagocardosoweb**
You had a misspelling typo.

### CODE REVIEW

**Comment by Guad** [comment]
This will break a lot of projects that depend on this method. Maybe add it in tandem with scripthookvdotnet 3.0?

**Comment by tiagocardosoweb** [comment]
There is a another solution, add this fix and the old method call this new one :)

So there will be 2 methods
- GetScreenResolutionMaintainRatio() - New one
- GetScreenResolutionMantainRatio() - Calls the new one.

**Comment by Guad** [comment]
Good call, can you add an `[Obsolete("Use GetScreenResolutionMaintainRatio")]` attribute to `GetScreenResolutionMantainRatio`  too?

**Comment by Guad** [comment]
Thanks for contributing!

**Pull request merged**
