### PR TITLE
Shvdn3 performance

### PR DESCRIPTION
**Pull request by Tanjitsu**
Made some small adjustments to the main Draw method to speed it up.

Mainly moved calculations (that were not needed per frame) out of the loop.
added an internal bool reDraw for triggering recalculation for the draw method.

Moved control list into a static pre defined list instead of created each frame.
reduced native calls by using _ALL_CONTROL_ native.
simplified the enable needed control loops.

### CODE REVIEW

**Comment by Tanjitsu** [comment]
Forgot to leave my other pull request out of this branch :P

**Comment by Tanjitsu** [comment]
So far... this causes an Issue !
The menu changes selection so fast that its hard to change one, instead it changed multiple.
Might need to pop in a wait :P

**Comment by Guad** [comment]
Nice work! Thank you! I can check it out once I get home.

**Comment by Tanjitsu** [comment]
System.DivideByZeroException: Attempted to divide by zero.
   at NativeUI.UIMenu.DrawCalculations()
   at NativeUI.UIMenu.Draw()

When the menu is empty.

**Comment by Guad** [comment]
Since #68 and #69 are pretty much the same, I'll leave #69 one up since this one has #67 mixed in too

**Pull request closed without merging**
